/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */
/* PELIGRO NO EJECUTAR ESTA CONSULTA A MENOS QUE SEA PARA ESTABLECER NUEVA BD */


 
drop table color;
drop table cuenta;
drop table edicion;
drop table estado_partida;
drop table jugador;
-- drop table link; ESTA NO DIEGO
drop table partida;
drop table propiedad;
drop table propiedad_partida;
drop table tipo_cuenta;
drop table tipo_propiedad;
drop table tipo_transaccion_monetaria;
drop table transaccion_monetaria;
drop table transaccion_propiedad;