
on: push
name: Publish Website to CPanel
jobs:
  FTP-Deploy-Action:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: get lastest code
      uses: actions/checkout@v3
      
    - name: sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        ftp-server: ${{secrets.FTP_SERVER}}
        ftp-username: ${{secrets.FTP_USERNAME}}
        ftp-password: ${{secrets.FTP_PASSWORD}}
