
on: 
  push:
    branches: [produccion]
name: Deploy PROD
jobs:
  FTP-Deploy-Action:
    if: github.ref_name == 'produccion'
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          STARTED DEPLOY:
          Repository: ${{ github.repository }}
          Autor: ${{ github.actor }} 
          Commit: ${{ github.event.commits[0].message }}

          Ver cambiso: https://github.com/${{ github.repository }}/commit/${{github.sha}}

    - name: get lastest code
      uses: actions/checkout@v3
      
    - name: sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          fileToExclude.txt
          **/vendor/**
          
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          FINISHED DEPLOY:
          Repository: ${{ github.repository }}
          Autor: ${{ github.actor }} 
          Commit: ${{ github.event.commits[0].message }}

          Ver cambiso: https://github.com/${{ github.repository }}/commit/${{github.sha}}
