
on: 
  push:
    branches: [master]
name: Publish Website to CPanel
jobs:
  FTP-Deploy-Action:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: get lastest code
      uses: actions/checkout@v3
      
    - name: sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          fileToExclude.txt
          **/vendor/**


    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: ${{secrets.MAIL_CONNECTION}}
        server_address: mail.maracsoft.com
        server_port: 465
        secure: true
        subject: Github Actions job result
        to: maracsoft@gmail.com
        from: Deploys Autom <deploys@maracsoft.com>
        body: Build job of ${{github.repository}} COMMIT ${{github.sha}}  ${{github.ref}}  completed successfully!
          

    
